### ISSUE TITLE
Larger inconsistency in operator values

### ISSUE THREAD

**Issue by paulferlitz** [billy-yoyo/RainbowSixSiege-Python-API#57]
For the biggest part this API works very well, thanks!

But I noticed many false values during my first few test runs.
I mainly tested with Smoke's values which were all over the place, his XP are those of Melusi, DBNOs are those of Maverick ...

<img width="668" alt="Screenshot 2020-09-16 at 05 42 22" src="https://user-images.githubusercontent.com/26034195/93289792-8935e600-f7df-11ea-8987-109d8e49855b.png">
Just a few examples where the numbers just don't add up. I check my values with R6 Tracker.

Could this be a problem on my end as I e.g. haven't yet unlocked Melusi in the actual game?

If you could get in touch with me, I would love to learn how you gathered all the information for this API and maybe improve it.

**Comment by billy-yoyo** [comment]
No these issues have existed in the API directly, just to clarify unlike R6 tracker this is not interfacing with some custom API I've written, this is simply a library to make it easier to pull data directly from Ubisoft's servers. I'm not really sure what causes these errors, the API is unstable at best, but can be due to my library doing things wrong (like ubi updating the names of object keys in the responses or similar). 

I can do a bit of investigation when I have some time in to why errors like this appear

**Comment by paulferlitz** [comment]
Ah okay I see, thanks for the clarification!
