### ISSUE TITLE
Can't get examples to work, let alone the API

### ISSUE THREAD

**Issue by AtomicProgramming** [billy-yoyo/RainbowSixSiege-Python-API#61]
So if I am correct, the authentication uses valid uplay details which I have provided, however I believe I know the issue and I am wondering if it is the case.

I am currently running python 3.9, and a lot of the module is outdated, what python version should I be using, as none is specified

**Comment by billy-yoyo** [comment]
Will work on getting the library working with the API over the next few weeks. The library aims to support python 3.4+, but it's possible we'll be dropping 3.4 and supporting 3.5+.

I'm going to close this since it's not a specific issue, but rather a general one which will be covered by a new issue tracking the updates of the library to the new API.
